name: Release mit Datum & Latest

on:
  push:
    branches:
      - main

permissions:
  contents: write  

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Datum generieren
        id: date
        run: echo "TIMESTAMP=$(date +'%Y-%m-%d-%H%M')" >> $GITHUB_ENV

      - name: Zip erstellen
        run: |
          zip -r arcxp-plugin-${{ env.TIMESTAMP }}.zip components/chains/article-body/ components/features/TickarooLiveblogPowerUp/ content/sources/tickaroo-liveblog.js environment/index.json -x "*.git*"
          cp arcxp-plugin-${{ env.TIMESTAMP }}.zip arcxp-plugin-latest.zip

      - name: Historisches Release erstellen
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.TIMESTAMP }}
          name: Release ${{ env.TIMESTAMP }}
          files: arcxp-plugin-${{ env.TIMESTAMP }}.zip
          draft: false
          prerelease: false
          make_latest: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update 'latest' Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release delete latest --cleanup-tag -y || true
          sleep 2
          gh release create latest arcxp-plugin-latest.zip \
            --title "Latest Release" \
            --notes "This is always the latest release from the main branch." \
            --latest \
            --target main